GET http://localhost:5555

###

POST  http://localhost:5555/login

###

POST  http://localhost:5555/register
Content-Type: application/json

{
    "username": "roshan",
    "email": "ros@gmail.com",
    "password": "Tim@002"
}

###

POST http://localhost:5555/